services:
  # --------- OpenTelemetry Collector ---------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    depends_on:
      tempo:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    command: [ "--config=/etc/otelcol-config.yml", "--feature-gates=pkg.translator.prometheus.NormalizeName"]
    ports:
      - 8888:8888
      - 8889:8889
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http
    volumes:
      - ./otel-collector/otelcol-config.yml:/etc/otelcol-config.yml
    networks:
      - fluxin-network

  # --------- Prometheus ---------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1h
      - --web.enable-remote-write-receiver
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
    ports:
      - 9090:9090
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1
      interval: 5s
      retries: 10
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - fluxin-network

  # --------- Grafana ---------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 5s
      retries: 10
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    networks:
      - fluxin-network

  # --------- Grafana Loki ---------
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - ./loki/data:/loki
    networks:
      - fluxin-network

  # --------- Grafana Tempo ---------
  init-tempo:
    image: &tempoImage grafana/tempo:latest
    restart: no
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo/data:/var/tempo

  tempo:
    image: *tempoImage
    container_name: tempo
    restart: unless-stopped
    depends_on:
      - init-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - 3200:3200   # tempo
      - 9095:9095 # tempo grpc
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3200/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml:ro
      - ./tempo/data:/var/tempo
    networks:
      - fluxin-network
